version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile
  build:
    commands:
      - pnpm run build:prod

artifacts:
  files:
    - '**/*'
  base-directory: dist
